#!/bin/bash
#
#                                       

##################################################################################################################
# If the option -y has been added. It will autoinstall all. Omit if you do not want that.
##################################################################################################################
#
#
#
#
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. AT YOUR OWN RISK.
#
##################################################################################################################

#stop firefox from saying well this is embarrasing -- stop restore of websites

about:config

browser.sessionstore.resume_from_crash  from true to false
browser.sessionstore.max_resumed_crashes from 0 to 1
